# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: '[Super Duper Fantastic]'
email: suki@superduperfantastic.com
description: A lifestyle/personal blog exploring food, travel and unique experiences and adventures in San Francisco and around the world. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://superduperfantastic.com" # the base hostname & protocol for your site
twitter_username: suki
github_username: superduperfantastic
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
gems: [jekyll-paginate, jekyll-archives]

# Output
permalink: /:title/
paginate: 12

# We don't want Rakefile to be published
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

#Archives Configuration
jekyll-archives:
    enabled: [year]
    layout: archive
    permalinks:
        year: '/:year/'
        